version: 2.1

orbs:

  nx: nrwl/nx@1.0.0

jobs:

  main:
    steps:
      - checkout
      - run: yarn install
      - nx/set-shas
      - run: npx nx affected --base=$NX_BASE --target=lint --parallel=3
      - run: npx nx affected --base=$NX_BASE --target=test --parallel=2

  pr:
    steps:
      - checkout
      - run: yarn install
      - nx/set-shas
      - run: npx nx affected --base=$NX_BASE --target=build --parallel=3
      - run: npx nx affected --base=$NX_BASE --target=lint --parallel=2

workflows:
  build:
    jobs:
      - main:
          filters:
            branches:
              only: main

      - pr:
          filters:
            branches:
              ignore: main
