version: 2.1

orbs:
  nx: nrwl/nx@1.0.0
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  main:
    docker:
      - image: cimg/node:17.5.0

    steps:
      - checkout
      - run: yarn install
      - nx/set-shas
      - run: npx nx affected --base=$NX_BASE --target=lint --parallel=3
      - run: npx nx affected --base=$NX_BASE --target=test --coverage --coverageReporters=lcov --parallel=2
      - run: node ./tools/coverageMerger.js
      - sonarcloud/scan

  pr:
    docker:
      - image: cimg/node:17.5.0

    steps:
      - checkout
      - run: yarn install
      - nx/set-shas
      - run: npx nx affected --base=$NX_BASE --target=build --parallel=3
      - run: npx nx affected --base=$NX_BASE --target=lint --coverage --coverageReporters=lcov --parallel=2
      - run: node ./tools/coverageMerger.js
      - sonarcloud/scan

workflows:
  build:
    jobs:
      - main:
          filters:
            branches:
              only: main
          context: SonarCloud

      - pr:
          filters:
            branches:
              ignore: main
          context: SonarCloud
